### ISSUE TITLE
useless if statement i think on line 294 [libraries/assets.php]

### ISSUE THREAD

**Issue by zaherg** [bstrahija/assets-ci#1]
is there any need for [ if statement ] on line [294]
// Combine
if ($type == 'css' and $this->less_css)
{
    //$data .= $contents;
    $data .= $this->_process($contents, $type, 'minify', $base_url);
}
else
{
    $data .= $this->_process($contents, $type, 'minify', $base_url);
}
i still think its the same with or without the if

**Comment by bstrahija** [comment]
I guess you're right, will take a look at this tonight.
