### ISSUE TITLE
adding a prefix to the cache files

### ISSUE THREAD

**Issue by zaherg** [bstrahija/assets-ci#10]
i was wondering since you didnt push the version yet ..
why not to add an option which will help to add a prefix to the combined ( or the single ) cached files, instead of using the time stamp ..

i will try to do it if you like me to help ...

**Comment by bstrahija** [comment]
I've been actually working on this feature before, so I have included it in the last commit. You can define the prefixes in the config or add them after through:

```
Assets::set_prefix('test.css.prefix', 'css');
Assets::set_prefix('test.js.prefix', 'js');
```

There's also an option in the config to remove the timestamp prefix if you want to.

**Comment by zaherg** [comment]
thanks .. i used the last one which you commit 7 h ago which does not have those options ..

any way thanks for your effort .. :D
