### ISSUE TITLE
cache auto cleared every time i go to a new page

### ISSUE THREAD

**Issue by zaherg** [bstrahija/assets-ci#11]
hi:
i have just downloaded your latest code ..
for some reason the cache was auto cleared whenever i go to a new page
here is my cache config options :

``` php
<?php
$config['assets']['auto_clear_cache']     = false;
$config['assets']['auto_clear_css_cache'] = false;
$config['assets']['auto_clear_js_cache']  = false;
```

**Comment by zaherg** [comment]
the files was cleared even before the execution of _cache_assets function ...

am working on windows 7 with xampp

**Comment by zaherg** [comment]
by the way i have just noticed that everything will work as it should when your configurations is like this

``` php
<?php
$config['assets']['combine_css'] = false;
$config['assets']['minify_css']  = false;
$config['assets']['combine_js']  = true;
$config['assets']['minify_js']   = false;
```

other wise it will delete the cached files and reproduce the same files again ..
for some reason am still cant figure it out why the lines 744 and 751 is called before checking if the files exists ..
the file is deleted then this function on line 372 called ..

**Comment by bstrahija** [comment]
Can you show me your code when you call the css() and js() methods (Assets::css() and Assets::js())?

**Comment by bstrahija** [comment]
And are you absolutely sure you have the latest version of the code? The one with CoffeeScript support?

**Comment by zaherg** [comment]
for the code 

``` php
  <?php Assets::css_group('head',array('bootstrap.css','style.css')); ?>
  <!-- end CSS-->
  <?php Assets::js_group('head',array('modernizr-2.0.6.min.js'));?>
```

and also i tried

``` php
  <?php Assets::css(array('bootstrap.css','style.css')); ?>
  <!-- end CSS-->
  <?php Assets::js(array('modernizr-2.0.6.min.js'));?>
```

and yes i have the latest code with coffee support , i download it from your repo

**Comment by bstrahija** [comment]
This is weird because it works on my local MAMP setup, and also on a test server. I don't have a Windows machine to test it on WAMP, will do it a little bit later. Perhaps your server time isn't set correctly?

Can you give me the filenames of the generated cache files?

**Comment by zaherg** [comment]
i dont think its something related to the file name since as i told you before the files were deleted before checking the lastmodified var which you use ..
any way the name of the file is :

``` bash
head.20120327220729.js
footer.20120402132034.js
```

**Comment by zaherg** [comment]
and i just noticed, that this option has no effect at the the same file name regenerated again 

``` php
<?php
$config['assets']['prefix_timestamp'] = false;
```

``` bash
head.20120327220729.js
footer.20120402132034.js
```

**Comment by bstrahija** [comment]
@linuxjuggler Can you check you're not calling the Assets::clear_cache() method somewhere? I just tried it on a default WAMP setup and everything works without problems. Do you have any errors or warnings in your log?

Regarding the prefix_timestamp option, this will only work if you enable custom css or js prefixes in the config. But I see your point, it could be usefull when using groups. Have to think about this one.

**Comment by zaherg** [comment]
am sure i didnt use it .. the only place i use your code is within my layout file ..
and there is no errors in my log file , you can check it http://pastebin.com/9LUGeh8R

any way i will try to upload my project to a linux server and monitor it ..

**Comment by zaherg** [comment]
there is one thing i had to say that am using it as a spark so i have changed the version to be 1.0.0 as you stated in your code..

```
sparks/assets/1.0.0/ 
```

**Comment by zaherg** [comment]
i have got your latest code from sparks .. deleted my old 1.0.0
and the same issue stay , the cache is auto cleared  ..
one thing is that my config file is inside config/development/ folder ( but i dont think this is an issue ) 

any way i didnt test it yet on a linux server ..
