### ISSUE TITLE
auto clear bug

### ISSUE THREAD

**Issue by laurencei** [bstrahija/assets-ci#14]
Hi,

I think there is a bug/possible design flaw:

Scenario: "auto_clear_cache = true"

Page 1:
css_group ("page1", "page1.css")

Page 2:
css_group ("page 2", "page2.css")

When you visit page 1, Page 2 CSS is deleted (because it created a new cache). When you visit Page 2, Page 1 cache is deleted (since you made a new cache). This continues on forever, unless you notice!!!!

This is poorly designed - perhaps it should be only delete Page 1 css file and vice versa?

**Comment by bstrahija** [comment]
I don't think there's a simple solution to this problem right now. The whole library is designed to be as simple as possible.

You are always welcome to contribute with a solution of your own, since I currently don't have much time to work on this spark.

**Comment by bstrahija** [comment]
I just added a possible fix to this problem, so can you please check out the develop branch?

When a file changes in a non-group assets list, all the files will be cleared, but when a file changes in a group, only the files with the prefix of the group will be deleted.

**Comment by laurencei** [comment]
cool - looks good!

**Comment by bstrahija** [comment]
Ok, closing the ticket for now.
