### ISSUE TITLE
Assets:: calls in nested templates generate incorrect paths

### ISSUE THREAD

**Issue by ehaughee** [bstrahija/assets-ci#15]
# Environment
- PHP 5.3
- CI 2.1.0
- Assets 1.5.0 (installed with sparks)

I am using the following template library:

``` php
<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Template {
        var $template_data = array();

        function set($name, $value)
        {
            $this->template_data[$name] = $value;
        }

        function view($view, $view_data = array(), $return = FALSE)
        {
            $this->CI =& get_instance();
            $this->load('template', $view, $view_data, $return);
        }

        function load($template = '', $view = '' , $view_data = array(), $return = FALSE)
        {
            $this->CI =& get_instance();
            $this->set('contents', $this->CI->load->view($view, $view_data, TRUE));

            return $this->CI->load->view($template, $this->template_data, $return);
        }
}
```
# Issue

When I render a template with a call to $this->template->view(), the images loaded in the partial get root paths (i.e. /image.png) causing them to be inaccessible, whereas images in the template get rendered with the full and appropriate path/url (i.e. http://sub.domain.tld/assets/img/image.png).

Any idea as to why this would be occuring?
# Update

After source-diving a bit in assets.php, it appears as though _set_path() does not get called when rendering the partial but waits until the template gets rendered.  However, the Assets::img function gets called when rendering the partial and returns a root path because `self::$img_url` is null.  Thus, after this line `$img_path = reduce_double_slashes(self::$img_url.'/'.$path);`, `$img_path` is just '/img_name.ext'.
# Update 2

I found that changing `Assets::img` to call `self::init();` at the top of its scope fixes the issue.

`Assets::img` now looks like this:

``` php
<?php

/**
* Return url to image, or event an entire tag
* @param  string $path
*/
public static function img($path = null, $tag = false, $properties = null)
{
    self::init();  // ADDED THIS LINE

    $img_path = reduce_double_slashes(self::$img_url.'/'.$path);

    // Properties
    if ($properties) $properties['src'] = $img_path;

    log_message('error', $img_path);

    // Tag?
    if ($tag) return img($properties);
    else      return $img_path;
}

?>
```

**Comment by bstrahija** [comment]
I added the self::init() call to the img method. This will be included in the next version. Thank you
