### ISSUE TITLE
CSSMin Config

### ISSUE THREAD

**Issue by laurencei** [bstrahija/assets-ci#16]
CSSMin has a number of config options -see here: http://code.google.com/p/cssmin/wiki/MinifierConfiguration.

Do you think we could have them included in the "assets" config file somehow - so we can set them there?

I'm forced to alter the library with my cssmin config - because the default config breaks my css during minification.

Either way - great library - thanks!

**Comment by bstrahija** [comment]
It's in the latest commit. Please test this before I tag it.

**Comment by laurencei** [comment]
cool - seems to be working well!
