### ISSUE TITLE
first time execution produce this error

### ISSUE THREAD

**Issue by zaherg** [bstrahija/assets-ci#19]
hi,
am using version 1.5.0. and the first time i execute the page i got this error

```
A PHP Error was encountered
Severity: Runtime Notice

Message: Creating default object from empty value

Filename: libraries/assets.php

Line Number: 771
```

and it will goes away once the info.cache was created ..

**Comment by bstrahija** [comment]
Could you give me the code where you add assets in your view, so I can try to replicate it?

**Comment by zaherg** [comment]
first of all here is my component :
1- CI 3.0-dev
2- MX HMVC
3-Template library from phill

``` php
<?=Assets::css_group('header',array('bootstrap.css','960_24_col.css','style.css'));?>
```

``` php
<?php

/*
|--------------------------------------------------------------------------
| Processing assets
|--------------------------------------------------------------------------
|
| Flags for processing actions
|
*/

$config['assets']['minify_css']           = false;
$config['assets']['minify_js']            = false;
$config['assets']['enable_less']          = false;
$config['assets']['enable_coffeescript']  = false;
$config['assets']['freeze']               = false;

/*
|--------------------------------------------------------------------------
| Cache
|--------------------------------------------------------------------------
|
| Define if the cache folder should be cleared when generating new cache files
| 
*/

$config['assets']['auto_clear_cache']     = false;
$config['assets']['auto_clear_css_cache'] = false;
$config['assets']['auto_clear_js_cache']  = false;

/*
|--------------------------------------------------------------------------
| Default paths and directories, tags
|--------------------------------------------------------------------------
|
| Default directories containing the assets
| Option to use HTML5 tags
|
*/

$config['assets']['assets_dir'] = 'themes/site/assets';
$config['assets']['js_dir']     = 'js';
$config['assets']['css_dir']    = 'css';
$config['assets']['cache_dir']  = 'cache';
$config['assets']['img_dir']    = 'img';
$config['assets']['html5']      = true;

```

and just a note that your code will combine my css / js files without any option not to do so ..
you have remove it from the config file right ?

**Comment by bstrahija** [comment]
I couldn't replicate the error, but I guess the problem is with an empty object. What type of error_reporting do you have setup? I pushed a new fix so please take a look if it fixes the bug.

**Comment by zaherg** [comment]
here is the Backtrace

``` php
A PHP Error was encountered

Severity: Runtime Notice

Message: Creating default object from empty value

Filename: libraries/assets.php

Line Number: 771

Backtrace:

File: app\libraries\assets.php
Line: 771
Function: _exception_handler

File: app\libraries\assets.php
Line: 474
Function: _update_cache_info

File: app\libraries\assets.php
Line: 120
Function: _process
```

**Comment by bstrahija** [comment]
Could you please download the latest version from github? I see you're still trying 1.5.0, there are some bugfixes waiting for 1.5.1

**Comment by zaherg** [comment]
the new update works like a charm .. thanks ..

**Comment by zaherg** [comment]
by the way you didnt update  the version 

``` php
define('ASSETS_VERSION', '1.5.0');
```

**Comment by bstrahija** [comment]
If you find anything else just report it. I'm still testing everything before I tag it with 1.5.1

**Comment by zaherg** [comment]
i will, but the combine option is missing :( ..

why did you remove it

**Comment by bstrahija** [comment]
Because I don't really see it being useful. The purpose of the spark is to reduce the number of requests and the size of the files.

Do you have an example when turning of combine would be useful?

**Comment by zaherg** [comment]
to be honest only in development, since you need to know where the error and where to change it  .. 

and i have this issue which am not sure if it has change in the new version ..
if i have backend / frontend when clearing the cache or regenerate the cache for one section it will clear the cache for the other one, even if they have a differ group name ..

**Comment by zaherg** [comment]
plus i have this issue which i think related to less.php, whenever i have filter inside the css it will throw an error

**Comment by bstrahija** [comment]
I will have to see if I can find some time to put the combine option back in.

The frontend/backend issue is solved in a different way for me. I use the default config for the backend, and for the frontend I have a different configuration:

```
Assets::init(array(
        'assets_dir' => 'addons/theme/assets',
        'js_dir'     => 'js',
        'css_dir'    => 'css',
        'cache_dir'  => 'cache',
        'img_dir'    => 'img',
        'minify_css' => false,
        'freeze'     => false,
    ));
```

I have separate controllers (Front and Backend) and each can have a different config.

**Comment by zaherg** [comment]
thats look nice ..

i will try to implement this once i update the project ..

thanks

**Comment by bstrahija** [comment]
Yes, I need to update the docs regarding the "freeze" option. This basicly tells the lib not to scan the files and folders for new and changed files, but to pull all the info from the info.cache file. This speeds up the whole process a little bit. Useful for apps with a bigger load in production.

**Comment by zaherg** [comment]
thanks for the explanation ..
if you would like i can fork the current version and send you a push for the docs, i will try my best to make it good :D

**Comment by bstrahija** [comment]
Sure, do it :)

**Comment by zaherg** [comment]
i just test it will bootstrap.less version 2.0.4 and it works like a charm
