### ISSUE TITLE
CSS Minify problem with twitter bootstrap pull-right

### ISSUE THREAD

**Issue by umefarooq** [bstrahija/assets-ci#26]
Hi i am using this library its great but facing one problem while minify twitter bootstrap css its not showing pull-right css at all in minified css, i have used this library in my two projects with twitter bootstrap facing same problem.

**Comment by bstrahija** [comment]
This is not a problem with CSS Min, but with the LessPHP library. I updated to the latest version so check it out if it's ok now. I'm closing the isssue .
