### ISSUE TITLE
Protocol-relative URL bug on IE

### ISSUE THREAD

**Issue by nyangry** [bstrahija/assets-ci#28]
libraries/assets.php on Line: 613
`$new_href = str_replace("http://", "//", $new_href);`

This code causes problem that IE can't load url.

reference: http://stackoverflow.com/questions/7408189/protocol-relative-url-in-css-for-multiple-subdomains

**Comment by bstrahija** [comment]
This should be fixed in the latest version, please test it so I can tag the new version ;)
