### ISSUE TITLE
Absolute paths in complied CSS

### ISSUE THREAD

**Issue by chrstphrknwtn** [bstrahija/assets-ci#34]
When CSS is called like this is a view:

```
<? Assets::css_group('application', array('application.css', 'vendor.css')); ?>
```

Image URLs are given absolute paths, so if an image path is specified in the CSS as:

```
.selector {
  background-image: url('/assets/img/ui/header-logo.png');
}
```

it becomes something like this:

```
.selector {
  background-image: url('http://10.0.0.43/assets/img/ui/header-logo.png');
}
```

So when developing and testing the site on different machines and devices, some with localhost some with an IP address, these links break on one or the other... depending on which visited first and created a the CSS in the cache.

Is there a way to turn this off?

**Comment by stevenwoodson** [comment]
By default Assets uses Codeigniter's **$config['base_url']** value to determine the URL for your assets. However this can be overwritten by defining the following configuration item: **$config['assets']['base_url'] = 'https://example.com';**

My suggestion would be to set either  **$config['base_url']** or **$config['assets']['base_url'] = ''** programmatically to match your environment or leave them both empty and allow Codeigniter to guess the base path which has always worked for me.

**Comment by chrstphrknwtn** [comment]
Hey Steven, 

Your suggestion appears to the best approach; programatically defining `$config['assets']['base_url']` based on the environment: development, testing or production.

Thanks.
