### ISSUE TITLE
feature request .. combine_css and combine_js

### ISSUE THREAD

**Issue by zaherg** [bstrahija/assets-ci#5]
is there a way to combine the css files without combine the js ?? since the config option combine everything when you turn it on .

**Comment by bstrahija** [comment]
It's inside the latest version. Still not tagged though, so I would appreciate some testing ;)

**Comment by zaherg** [comment]
waiting .. thanks ..

**Comment by zaherg** [comment]
i have test it on my development environment and its working like a charm ...

didnt test the group yet nor the less functionality ( but i will during the day  )  ..

thanks for your effort ...
