### ISSUE TITLE
Autoloading Not working in 2.1.0

### ISSUE THREAD

**Issue by inverse** [bstrahija/assets-ci#6]
I am in the process of upgrading to 2.1.0 and after following the instructions in the CodeIgniter documentation I now get the following error:

**Fatal error: Call to undefined function display_css()**
## Update

It would appear the problem is only when this spark is being autoloaded. So I believe it is something to do with the Sparks ci_autoloader and not an asset related issue.

**Comment by zaherg** [comment]
am working on a project with assets spark version and CI 2.1  and i didnt have this problem ..

**Comment by inverse** [comment]
Are you auto-loading the spark?

**Comment by inverse** [comment]
It was an issue with sparks
