### ISSUE TITLE
Parsing LESS files

### ISSUE THREAD

**Issue by ghost** [bstrahija/assets-ci#9]
This is the first time I have ever used github, so apologies if this is not the correct place for asking questions (if so, perhaps you could point me in the right direction).

I've just setup assets in my CI project and it's great. However, I can't work out how to make use of the LESSPHP facility. I've use it outside of CI in the past, but I'm new to CI also.

Where would I put the .less files and what's the command to compile the .less to .css?

Any pointers would be much appreciated.

Thanks.

**Comment by bstrahija** [comment]
Less parsing occurs automatically if it's enabled in the config file. Simply add your less files to the array in the display_css() function.

I'm currently working on a new version that will be more LESS friendly and will support @import inside the less files. I just hope it wont take to long to finish it ;)
